const today = new Date();
const year = today.getFullYear();
const month = today.getMonth();
const day = today.getDate();

export const eventosPadrao = [
  {
    id: 1,
    title: "Atividade",
    start: new Date(year, month, day, 10, 0),
    end: new Date(year, month, day, 12, 0),
    desc: "Primeiro evento",
    autor: "Pedro Silva",
    setor: "DiretorTecnico",
    tipo: "atividade",
    status: "pendente",
  },
  {
    id: 2,
    title: "Reunião",
    start: new Date(year, month, day + 1, 14, 0),
    end: new Date(year, month, day + 1, 16, 0),
    desc: "Segundo evento",
    setor: "DAF",
    autor: "João Melo",
    tipo: "reuniao",
    status: "pendente",
    local: "presencial",
    sala: "sala-reuniao",
  },
  {
    id: 3,
    title: "Documento",
    start: new Date(year, month, day + 2, 14, 0),
    end: new Date(year, month, day + 2, 16, 0),
    desc: "Terceiro evento",
    setor: "Presidente",
    autor: "João Melo",
    tipo: "documento",
    status: "pendente",
  },
  {
    id: 4,
    title: "Atividade Externa",
    start: new Date(year, month, day + 3, 14, 0),
    end: new Date(year, month, day + 3, 16, 0),
    desc: "Quarto evento",
    setor: "DAF",
    autor: "João Melo",
    tipo: "atividades-externas",
    status: "pendente",
  },
  {
    id: 5,
    title: "Reunião Ordinária Direx",
    start: new Date(year, month, day + 4, 9, 0),
    end: new Date(year, month, day + 4, 11, 0),
    desc: "Reunião mensal da Diretoria Executiva para análise de resultados e tomada de decisões estratégicas",
    setor: "Diretoria Executiva",
    autor: "Presidente",
    tipo: "reuniao-direx",
    status: "agendada",
    prioridade: "alta",
    local: "presencial",
    sala: "auditorio",
  },
  {
    id: 6,
    title: "Reunião de Planejamento",
    start: new Date(year, month, day + 1, 15, 0),
    end: new Date(year, month, day + 1, 17, 0),
    desc: "Reunião para planejamento trimestral - conflito com sala existente",
    setor: "Planejamento",
    autor: "Maria Silva",
    tipo: "reuniao",
    status: "agendada",
    local: "presencial",
    sala: "sala-reuniao",
  },
];
